name: build intercal code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get C-INTERCAL
        run: sudo apt-get install -y intercal
      - uses: mymindstorm/setup-emsdk@v14
      - name: compileth codeth
        run: |
          tree
          ick -ceb ./src/hello.i
          mv ./src/hello.c ./hello.c
          cd libick
          LIBICKSRC=$(find . -name '*.c')
          emcc ../hello.c ../libs/customdom.c $LIBICKSRC -I. -o ../hello.js -sEXPORTED_FUNCTIONS=_main -sSTANDALONE_WASM=1 -sEXIT_RUNTIME=1 -sALLOW_MEMORY_GROWTH=1 -sENVIRONMENT=web -sMODULARIZE=1
          cd ..
          ls -l hello.js
          tree
      - uses: actions/upload-artifact@v4
        with:
          path: hello.js
