name: build intercal code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get C-INTERCAL
        run: sudo apt-get install -y intercal
      - name: compileth codeth
        run: |
          tree
          ick -bc ./src/hello.i
          mv ./src/hello.c ./hello.c
          ls -l hello.c
      - uses: actions/upload-artifact@v4
        with:
          path: hello.c
