name: build intercal code
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get C-INTERCAL
        run: sudo apt-get install -y intercal && ls
      - name: compileth codeth
        run: |
          tree
          cat ./src/hello.i
          ick -bc ./src/hello.i
          tree
      - uses: actions/upload-artifact@v4
        with:
          path: ./src/hello.c
